var app = new GeoExplorer({
				wms: '/geoserver/wms',
				map: {
						projection: 'EPSG:900913',
						maxResolution: 156543.0339,
						maxExtent: [
                        -20037508.34, -20037508.34,
                        20037508.34, 20037508.34
						],
						center: [0, 0],
						zoom: 1,
						layers: [{
				name: 'argis:asset',
				title: 'DEC Assets',
				originator: 'New York State Department of Environmental Conservation',
                                format: 'image/png',
				group: '',
				visibility: false,
				metadata: '',
				description: "",
				styles: '',
				slds: [],
				cql_filter: ,
				queries: [],
                                updated: '2012-05-25'
				},{
				name: 'argis:landclass2001',
				title: '2001 Land Use/Development Plan Map',
				originator: 'New York State Adirondack Park Agency',
                                format: 'image/png',
				group: 'historic',
				visibility: false,
				metadata: 'http://www.apa.state.ny.us/gis/shared/htmlpages/metadata/apalandclass.html',
				description: "Adirondack Park Land Use and Development Plan Map and State Land Map (APLUDP\/SLMP), circa 2001, produced by the Adirondack Park Agency. Contains polygon data representing state and private land classifications and open water. Mapped at various scales from tax maps and 1:24000 scale base maps.",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2006-10-01'
				},{
				name: 'argis:blowdown1950',
				title: '1950 Blowdown Map',
				originator: 'New York State Department of Environmental Conseration',
                                format: 'image/png',
				group: 'historic',
				visibility: false,
				metadata: 'http://aprgis.org/argis/metadata/1950blowdown.html',
				description: "This coverage contains areas damaged by a 1950 windstorm in and around the Adirondack Park, New York State.The data was created for the Adirondack Park Agency (APA) as an historical reference. This resource may be used to determine the recent history of land use and major disturbances in the Adirondack Park. The hardcopy map from which this digital data set was created is a creased paper blueprint developed by the New York State Conservation Department. According to the map, the areas of storm damage were determined from aerial reconnaissance data. The blueprint was drawn by the Forest General of the New York State Conservation Department, Gerald J. Rides. The scale bar indicates the map was drawn at a 1 inch = 4 miles scale. A legend appears at the bottom of the map with the following information:25-50% Blowdown\n50-100% Blowdown\nCounty lines\nAdirondack blueline\nState land\nThe 25-50% Blowdown category polygons are indicated by a pale dashed outline. These lines are very faint in some instances. A digital Arc\/Info interchange file containing a nearly complete representation of the 1950 Blowdown map was created by the staff from the Center for Remote Sensing at SUNY Plattsburg. The polygons on the original map were copied on to a cartographically correct 1:250,000 NYS DOT base map, then digitized. ",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2000-01-01'
				},{
				name: 'argis:firemap1916',
				title: '1916 Fire Protection Map',
				originator: 'Applied GIS/Adirondack Park Agency',
                                format: 'image/png',
				group: 'historic',
				visibility: false,
				metadata: 'http://aprgis.org/argis/metadata/ADK_1916_firemap.html',
				description: "This coverage contains the 1916 fire protection areas of the Adirondack Park, New York State.  The data was created for the Adirondack Park Agency (APA) as an historical reference. This resource may be used to determine the recent history of land use in the Adirondack Park and major disturbances to the landscape. Such known and documented disturbances include a series of major forest fires that occurred at the turn of the 19th Century.\n\n \n\nData is to be used at the scale intended (1:126720)\n\nUsage Notes: The hardcopy color map from which this digital data set was created is printed on paper adhered to a cloth\/linen backing and attached on the top and bottom to long wooden sticks. The different land codes are color-coded and described in the legend. Supplemental Information: Digital data was developed by for the area defined by the Oswegatchie\/Black River watershed in by SUNY Plattsburg in conduction with the APA.\n\n ",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2000-01-01'
				},{
				name: 'argis:fishsurveylakes',
				title: 'Fish Surveys',
				originator: 'NY State Department of Environmental Conservation,Division of Fish, Wildlife Marine Resources',
                                format: 'image/png',
				group: 'lakes',
				visibility: false,
				metadata: 'http://www.dec.ny.gov/outdoor/7927.html',
				description: "Fish surveys of selected Adirondack lakes.  Disclaimer of Warranties and Accuracy of Data, NYSDEC Bureau of Fisheries Modern Statewide Fisheries Database: No warranty, expressed or implied, is made regarding the validity, accuracy, adequacy, completeness, legality, reliability or usefulness of any information provided from this database. The data are provided on an \"as is\" basis. All warranties of any kind, express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, freedom from contamination by computer viruses and non-infringement of proprietary rights are disclaimed. Data can also quickly become out-of-date and changes may periodically be made to the information transmitted herewith; these changes may or may not be incorporated in any new version of the database or any information provided from said database. Be aware that electronic data can be altered subsequent to original distribution. If any errors or omissions are discovered, please report them to the person who supplied you the data.",
				styles: '',
				slds: [],
				cql_filter: "specieslist LIKE '%'",
				queries: [["All species", "specieslist LIKE '%'"], ["Unknown Spp", "specieslist LIKE '%*** Unknown Spp ***%'"], ["Alewife", "specieslist LIKE '%Alewife%'"], ["American Eel", "specieslist LIKE '%American Eel%'"], ["Atlantic Salmon", "specieslist LIKE '%Atlantic Salmon%'"], ["Banded Killifish", "specieslist LIKE '%Banded Killifish%'"], ["Black Bullhead", "specieslist LIKE '%Black Bullhead%'"], ["Black Crappie", "specieslist LIKE '%Black Crappie%'"], ["Blackchin Shiner", "specieslist LIKE '%Blackchin Shiner%'"], ["Bluegill", "specieslist LIKE '%Bluegill%'"], ["Bluntnose Minnow", "specieslist LIKE '%Bluntnose Minnow%'"], ["Bowfin", "specieslist LIKE '%Bowfin%'"], ["Brassy Minnow", "specieslist LIKE '%Brassy Minnow%'"], ["Bridle Shiner", "specieslist LIKE '%Bridle Shiner%'"], ["Brook Silverside", "specieslist LIKE '%Brook Silverside%'"], ["Brook Stickleback", "specieslist LIKE '%Brook Stickleback%'"], ["Brook Trout", "specieslist LIKE '%Brook Trout%'"], ["Brown Bullhead", "specieslist LIKE '%Brown Bullhead%'"], ["Brown Trout", "specieslist LIKE '%Brown Trout%'"], ["Burbot", "specieslist LIKE '%Burbot%'"], ["Central Mudminnow", "specieslist LIKE '%Central Mudminnow%'"], ["Chain Pickerel", "specieslist LIKE '%Chain Pickerel%'"], ["Channel Catfish", "specieslist LIKE '%Channel Catfish%'"], ["Cisco Or Lake Herring", "specieslist LIKE '%Cisco Or Lake Herring%'"], ["Common Carp", "specieslist LIKE '%Common Carp%'"], ["Common Shiner", "specieslist LIKE '%Common Shiner%'"], ["Creek Chub", "specieslist LIKE '%Creek Chub%'"], ["Creek Chubsucker", "specieslist LIKE '%Creek Chubsucker%'"], ["Cutlip Minnow", "specieslist LIKE '%Cutlip Minnow%'"], ["Eastern Blacknose Dace", "specieslist LIKE '%Eastern Blacknose Dace%'"], ["Eastern Sand Darter", "specieslist LIKE '%Eastern Sand Darter%'"], ["Eastern Silvery Minnow", "specieslist LIKE '%Eastern Silvery Minnow%'"], ["Emerald Shiner", "specieslist LIKE '%Emerald Shiner%'"], ["Fallfish", "specieslist LIKE '%Fallfish%'"], ["Fathead Minnow", "specieslist LIKE '%Fathead Minnow%'"], ["Freshwater Drum", "specieslist LIKE '%Freshwater Drum%'"], ["Gizzard Shad", "specieslist LIKE '%Gizzard Shad%'"], ["Golden Shiner", "specieslist LIKE '%Golden Shiner%'"], ["Goldfish", "specieslist LIKE '%Goldfish%'"], ["Grass Carp", "specieslist LIKE '%Grass Carp%'"], ["Grass Pickerel", "specieslist LIKE '%Grass Pickerel%'"], ["Greater Redhorse", "specieslist LIKE '%Greater Redhorse%'"], ["Green Sunfish", "specieslist LIKE '%Green Sunfish%'"], ["Highfin Carpsucker", "specieslist LIKE '%Highfin Carpsucker%'"], ["Iowa Darter", "specieslist LIKE '%Iowa Darter%'"], ["Johnny Darter", "specieslist LIKE '%Johnny Darter%'"], ["Lake Chub", "specieslist LIKE '%Lake Chub%'"], ["Lake Sturgeon", "specieslist LIKE '%Lake Sturgeon%'"], ["Lake Trout", "specieslist LIKE '%Lake Trout%'"], ["Lake Whitefish", "specieslist LIKE '%Lake Whitefish%'"], ["Largemouth Bass", "specieslist LIKE '%Largemouth Bass%'"], ["Leatherjack", "specieslist LIKE '%Leatherjack%'"], ["Lepomis Sp.", "specieslist LIKE '%Lepomis Sp.%'"], ["Lepomis sp", "specieslist LIKE '%Lepomis sp%'"], ["Logperch", "specieslist LIKE '%Logperch%'"], ["Longear Sunfish", "specieslist LIKE '%Longear Sunfish%'"], ["Longnose Gar", "specieslist LIKE '%Longnose Gar%'"], ["Longnose Sucker", "specieslist LIKE '%Longnose Sucker%'"], ["Margined Madtom", "specieslist LIKE '%Margined Madtom%'"], ["Mimic Shiner", "specieslist LIKE '%Mimic Shiner%'"], ["Minnow & Carp Family", "specieslist LIKE '%Minnow & Carp Family%'"], ["Mooneye", "specieslist LIKE '%Mooneye%'"], ["Moxostoma sp", "specieslist LIKE '%Moxostoma sp%'"], ["Muskellunge", "specieslist LIKE '%Muskellunge%'"], ["New World Silverside Family", "specieslist LIKE '%New World Silverside Family%'"], ["Northern Hog Sucker", "specieslist LIKE '%Northern Hog Sucker%'"], ["Northern Pike", "specieslist LIKE '%Northern Pike%'"], ["Northern Redbelly Dace", "specieslist LIKE '%Northern Redbelly Dace%'"], ["Pearl Dace", "specieslist LIKE '%Pearl Dace%'"], ["Pike Family", "specieslist LIKE '%Pike Family%'"], ["Pumpkinseed", "specieslist LIKE '%Pumpkinseed%'"], ["Rainbow Smelt", "specieslist LIKE '%Rainbow Smelt%'"], ["Rainbow Trout", "specieslist LIKE '%Rainbow Trout%'"], ["Redbreast Sunfish", "specieslist LIKE '%Redbreast Sunfish%'"], ["Redfin Pickerel", "specieslist LIKE '%Redfin Pickerel%'"], ["Rock Bass", "specieslist LIKE '%Rock Bass%'"], ["Rosyface Shiner", "specieslist LIKE '%Rosyface Shiner%'"], ["Round Goby", "specieslist LIKE '%Round Goby%'"], ["Round Whitefish", "specieslist LIKE '%Round Whitefish%'"], ["Rudd", "specieslist LIKE '%Rudd%'"], ["Sand Shiner", "specieslist LIKE '%Sand Shiner%'"], ["Satinfin Shiner", "specieslist LIKE '%Satinfin Shiner%'"], ["Sculpin Family", "specieslist LIKE '%Sculpin Family%'"], ["Sea Lamprey", "specieslist LIKE '%Sea Lamprey%'"], ["Shorthead Redhorse", "specieslist LIKE '%Shorthead Redhorse%'"], ["Silver Lamprey", "specieslist LIKE '%Silver Lamprey%'"], ["Silver Redhorse", "specieslist LIKE '%Silver Redhorse%'"], ["Slimy Sculpin", "specieslist LIKE '%Slimy Sculpin%'"], ["Smallmouth Bass", "specieslist LIKE '%Smallmouth Bass%'"], ["Sockeye Salmon", "specieslist LIKE '%Sockeye Salmon%'"], ["Splake", "specieslist LIKE '%Splake%'"], ["Spotfin Shiner", "specieslist LIKE '%Spotfin Shiner%'"], ["Spottail Shiner", "specieslist LIKE '%Spottail Shiner%'"], ["Stonecat", "specieslist LIKE '%Stonecat%'"], ["Sucker Family", "specieslist LIKE '%Sucker Family%'"], ["Sunfish Family", "specieslist LIKE '%Sunfish Family%'"], ["Tadpole Madtom", "specieslist LIKE '%Tadpole Madtom%'"], ["Tessellated Darter", "specieslist LIKE '%Tessellated Darter%'"], ["Tiger Musky", "specieslist LIKE '%Tiger Musky%'"], ["Tiger Trout", "specieslist LIKE '%Tiger Trout%'"], ["Trout Family", "specieslist LIKE '%Trout Family%'"], ["Trout-Perch", "specieslist LIKE '%Trout-Perch%'"], ["Walleye", "specieslist LIKE '%Walleye%'"], ["White Bass", "specieslist LIKE '%White Bass%'"], ["White Crappie", "specieslist LIKE '%White Crappie%'"], ["White Perch", "specieslist LIKE '%White Perch%'"], ["White Sucker", "specieslist LIKE '%White Sucker%'"], ["Yellow Bullhead", "specieslist LIKE '%Yellow Bullhead%'"], ["Yellow Perch", "specieslist LIKE '%Yellow Perch%'"]],
                                updated: '2012-02-16'
				},{
				name: 'argis:slt',
				title: 'DEC Trails',
				originator: 'New York State Department of Environmental Conservation',
                                format: 'image/png',
				group: 'recreation',
				visibility: false,
				metadata: 'http://www.nysgis.state.ny.us/gisdata/metadata/nysdec.rds_trls.xml',
				description: "Line data locating and differentiating transportation corridors on state DEC lands.",
				styles: '',
				slds: [],
				cql_filter: "foot <> 'H'",
				queries: [["All Uses", "foot <> 'H'"], ["Foot", "foot <> 'N'"], ["Horse", "horse <> 'N'"],["Ski", "xc <>= 'N'"],["Bike", "bike <> 'N'"],["Motor Vehicle", "motorv <> 'N'"],["Snowmobile", "snowmb <> 'N'"],["Handicap Accessible", "accessible <> 'N'"]],
                                updated: '2012-05-25'
				},{
				name: 'argis:wetlands',
				title: 'Wetlands',
				originator: 'New York State Adirondack Park Agency',
                                format: 'image/png',
				group: 'hydrography',
				visibility: false,
				metadata: 'http://www.apa.state.ny.us/gis/shared/htmlpages/data.html#wetl',
				description: "Wetlands of the Adirondack Park from airphoto interpretation, including a modified Cowardin classification according to the National Wetlands Inventory conventions.",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2010-12-01'
				},{
				name: 'ADKPUBLIC:alsc1992_2010',
				title: 'Lake Chemistry Data 1992-2010',
				originator: 'Adirondack Lakes Survey Corporation',
                                format: 'image/png',
				group: 'lakes',
				visibility: false,
				metadata: 'http://www.adirondacklakessurvey.org/',
				description: "In 1991, the ALSC developed a proposal to conduct a long-term monitoring program (LTM) for evaluating changes in water chemistry in a selected set of representative Adirondack waters. This project, funded by USEPA and others, began in the spring of 1992. The primary goal of this project was to evaluate the effectiveness of the Clean Air Act Amendments of 1990 (CAAA) which mandated significant reductions in sulfer dioxide (SO2) and oxides of nitrogen (NOx), pollutants that are responsible for acidic deposition. Research produced ongoing detailed assessment of temporal and spatial chemistry of waters located in the Adirondack region.",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2009-12-01'
				},{
				name: 'argis:campsite',
				title: 'Campsites',
				originator: 'New York State Department of Environmental Conservation',
                                format: 'image/png',
				group: 'recreation',
				visibility: false,
				metadata: '',
				description: "This dataset was created by querying the NYS DEC \"State Land Assets\" layer WHERE asset=\"PRIMITIVE CAMPSITE\"",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2012-05-25'
				},{
				name: 'argis:streams',
				title: 'Streams',
				originator: 'NY State Department of Environmental Conservation,Division of Fish, Wildlife Marine Resources',
                                format: 'image/png',
				group: 'hydrography',
				visibility: false,
				metadata: 'http://www.dec.ny.gov/outdoor/7927.html',
				description: "Division of Fish, Wildlife Marine Resources added state-wide Fisheries Identification Numbers (FINs) to the National Hydrography Dataset (NHD) flowline layer.",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2011-06-28'
				},{
				name: 'argis:landclass2012',
				title: '2012 Land Use/Development Plan Map (APA)',
				originator: 'New York State Adirondack Park Agency',
                                format: 'image/png',
				group: 'admin_boundaries',
				visibility: false,
				metadata: 'http://www.apa.state.ny.us/gis/shared/htmlpages/metadata/apalandclass.html',
				description: "Adirondack Park Land Use and Development Plan Map and State Land Map (APLUDP\/SLMP) produced by the Adirondack Park Agency. Contains polygon data representing state and private land classifications and open water. Mapped at various scales from tax maps and 1:24000 scale base maps.",
				styles: '',
				slds: [],
				cql_filter: "lccd < 15",
				queries: [["All Classes", "lccd < 15"],["Hamlet", "lccd = '1'"],["Moderate Intensity Use", "lccd = '2'"],["Low Intensity Use", "lccd = '3'"],["Rural Use", "lccd = '4'"],["Resource Management", "lccd = '5'"],["Industrial Use", "lccd = '6'"],["Wilderness", "lccd = '7'"],["Canoe Area", "lccd = '8'"],["Primitive Area", "lccd = '9'"],["Wild Forest", "lccd = '10'"],["Intensive Use", "lccd = '11'"],["Historic", "lccd = '12'"],["State Administrative", "lccd = '13'"],["Pending Classification", "lccd = '14'"]],
                                updated: '2011-04-01'
				},{
				name: 'argis:trailregisters',
				title: 'Trailhead Registers',
				originator: 'New York State Department of Environmental Conservation',
                                format: 'image/png',
				group: 'recreation',
				visibility: false,
				metadata: '',
				description: "This dataset was created by querying the NYS DEC \"State Land Assets\" layer WHERE asset=\"TRAILHEAD REGISTER\"",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2012-05-25'
				},{
				name: 'argis:aquaticinvasives',
				title: 'Aquatic Invasive Species (APIPP)',
				originator: 'Adirondack Park Invasive Plants Program',
                                format: 'image/png',
				group: 'invasives',
				visibility: false,
				metadata: 'http://www.adkinvasives.com/Aquatic/Maps/Maps.asp',
				description: "These data include information collected by APIPP volunteer plant monitors, as well as documentation provided by other monitoring or plant identification programs operating in the Adirondack Park. The latter include the Darrin Fresh Water Institute plant identification program, the N.Y. Dept. of Environmental Conservation's Citizens Statewide Lake Assessment Program (CSLAP), and reports from Paul Smith College's Adirondack Watershed Institute. It is important to note that methods for data collection may vary by program. Data definitions and methodological variations are documented in the APIPP meta-data summary. ",
				styles: '',
				slds: [],
				cql_filter: "species LIKE '%'",
				queries: [["All Species", "species LIKE '%'"], ["Curlyleaf Pondweed", "species='Curlyleaf Pondweed'"], ["Eurasian Watermilfoil", "species='Eurasian Watermilfoil'"], ["Fanwort", "species='Fanwort'"], ["Variable-Leaf Milfoil", "species='Variable-Leaf Milfoil'"], ["Water Chestnut", "species='Water Chestnut'"]],
                                updated: '2014-07-22'
				},{
				name: 'argis:citytown',
				title: 'Cities & Towns',
				originator: 'New York State Office of Cyber Security (OCS)',
                                format: 'image/png',
				group: 'admin_boundaries',
				visibility: false,
				metadata: 'http://www.nysgis.state.ny.us/gisdata/metadata/alis.civil_boundaries.city_town.xml',
				description: "A vector file of New York State incorporated city and town boundaries.",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2011-04-30'
				},{
				name: 'argis:lakes',
				title: 'Lakes',
				originator: 'SUNY-ESF Adirondack Ecological Center',
                                format: 'image/png',
				group: 'hydrography',
				visibility: false,
				metadata: 'http://aprgis.org/argis/metadata/AdirondackLakes.html',
				description: "This layer was created using a spatial SQL query on the Adirondack Park Agency's Land Use & Development Plan Map and accompanying \"WaterLUT\"  relate table, both available for download from this page:  http:\/\/apa.ny.gov\/gis\/index.html\n\n",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2011-04-01'
				},{
				name: ':',
				title: 'Hillshade 30m',
				originator: 'NASA',
                                format: 'image/png',
				group: '',
				visibility: false,
				metadata: 'http://aprgis.org/argis/metadata/adk_30m_dem.html',
				description: "Hillshade derived from 30m DEM  produced by USGS SRTM (Shuttle Radar Topography Mission) in the year 2000.  Elevation units are meters.\n\nData Downloaded from USGS Seamless Data Distribution Site:\nhttp:\/\/seamless.usgs.gov\/website\/seamless\/viewer.php\nPost-processing performed by Steve Signell, Adirondack Ecological Center in Nov. 2005:\n \n1. Data tiles downloaded from USGS site\n2. Tiles reprojected to UTM 18N.\n3. Tiles mosaicked to create a coverage for the entire Adirondack park with a 10k buffer.\n4.  Several small voids due to mountain shadows were filled using values from the 30m NED downloaded from the USGS Seamless site.",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2006-01-01'
				},{
				name: 'argis:watershedshuc8',
				title: 'Major Watersheds (HUC8)',
				originator: 'U.S. Federal and State Agencies',
                                format: 'image/png',
				group: 'hydrography',
				visibility: false,
				metadata: 'http://www.geodata.gov/E-FW/DiscoveryServlet?uuid={4BDFFA3C-710B-4A27-B8F5-A82C0F32FEE8}&xmltransform=metadata_details.xsl',
				description: "The Watershed Boundary Dataset (WBD) is a complete digital hydrologic unit national boundary layer that is at the Subwatershed (12-digit) level. It is composed of the watershed boundaries delineated by state agencies at the 1:24,000 scale. Please refer to the individual state metadata as the primary reference source. To access state specific metadata, go to the following link to view documentation created by agencies that performed the watershed delineation. ftp:\/\/ftp.ftw.nrcs.usda.gov\/pub\/wbd\/hu\/metadata.",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2011-03-18'
				},{
				name: 'argis:alschistoric',
				title: 'Lake Chemistry Data 1984-87',
				originator: 'Adirondack Lakes Survey Corporation',
                                format: 'image/png',
				group: 'lakes',
				visibility: false,
				metadata: 'http://www.adirondacklakessurvey.org/',
				description: "Reported water chemistry data are from the intensive lake chemistry survey conducted between the months of July and August from 1984 &#8211; 1987 as part of the larger Adirondack lakes survey of chemistry and fish. This intensive sampling took place in the summer when most Adirondack waters are typically stratified. When possible, the middle or deepest part of the lake was sampled to avoid the effects of littoral zones and inlet streams. Samples in isothermal waters were collected 1.5 meters below the surface or at mid-depth when the waters were less than 1.5 meters deep. In stratified waters, a sample was collected at 1.5 meters below the surface and also half way between the thermocline and the bottom. Chemical analysis was conducted at the Adirondack Lakes Survey Corporation (ALSC) laboratory in Ray Brook following EPA guidelines. Table 1 lists the chemical parameters analyzed and units of concentration reported.",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2001-07-16'
				},{
				name: 'argis:terrestrialinvasives',
				title: 'Terrestrial Invasive Species (APIPP)',
				originator: 'Adirondack Park Invasive Plants Program',
                                format: 'image/png',
				group: 'invasives',
				visibility: false,
				metadata: 'http://www.adkinvasives.com/terrestrial/Program/Program.html',
				description: "These data include information collected by APIPP volunteer plant monitors, as well as documentation provided by other monitoring or plant identification programs operating in the Adirondack Park. The latter include the Darrin Fresh Water Institute plant identification program, the N.Y. Dept. of Environmental Conservation's Citizens Statewide Lake Assessment Program (CSLAP), and reports from Paul Smith College's Adirondack Watershed Institute. It is important to note that methods for data collection may vary by program. Data definitions and methodological variations are documented in the APIPP meta-data summary. ",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2012-03-19'
				},{
				name: 'argis:blueline',
				title: 'Adirondack Park Boundary',
				originator: 'New York State Adirondack Park Agency',
                                format: 'image/png',
				group: 'admin_boundaries',
				visibility: true,
				metadata: 'http://www.apa.state.ny.us/gis/shared/htmlpages/metadata/blueline.html',
				description: "Adirondack Park Boundary. Polygon data produced by the Adirondack Park Agency. The legal Park boundary description is found in New York State Environmental Conservation Law Section 9-0101.",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '1993-09-14'
				},{
				name: 'ADK:**Blowdown1995',
				title: 'July 1995 Micro-Burst Map',
				originator: 'Geography Department of St. Lawrence University',
                                format: 'image/png',
				group: '',
				visibility: false,
				metadata: 'http://aprgis.org/argis/metadata/ADK_bdown95.html',
				description: "The Oswegatchie\/Black study area has been the scene of major natural disturbances documented in the proposal and incorporated in the basic data for the project. On July 15, 1995, a storm event impacted thousands of acres of forest, concentrated in the Five Ponds Wilderness area, but also distributed throughout the region, including significant areas of private forest. The Adirondack Park Agency proposed to evaluate the spatial extent of the damage and use of remote sensing techniques for quantitative analysis of the degree of damage in cooperation with Dr. William Elberty, chair of the Geography Department at St. Lawrence University. The project was amended to incorporate cooperative acquisition of Thematic Mapper images covering this area for the period August 1994 and August 1995. Acquisition was made possible by financial contributions from the NYS Department of Environmental Conservation (the lead agency for disaster response), St. Lawrence University Department of Geography, Niagara Mohawk Power Corporation and the Adirondack Park Agency.\nThe primary products of this effort are: 1) classified images using two different techniques to map the storm damage, also available in digital and printed formats; and 2) secondary analyses and documentation by Dr. Elberty as the data are used for teaching and student projects at St. Lawrence University. The primary data sets are owned by the Adirondack Park Agency and maintained at the Geography Department of St. Lawrence University.",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2006-01-01'
				},{
				name: 'argis:leantos',
				title: 'Lean-Tos',
				originator: 'New York State Department of Environmental Conservation',
                                format: 'image/png',
				group: 'recreation',
				visibility: false,
				metadata: '',
				description: "This dataset was created by querying the NYS DEC \"State Land Assets\" layer WHERE asset=\"LEAN-TO\"",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2012-05-25'
				},{
				name: 'argis:streamflow',
				title: 'USGS Streamflow (Real-Time)',
				originator: 'U.S. Geological Survey',
                                format: 'image/png',
				group: 'hydrography',
				visibility: false,
				metadata: 'http://waterwatch.usgs.gov/index.php',
				description: "U.S. Geological Survey (USGS) current streamflow conditions for the NY State. The real-time information generally is updated on an hourly basis. ",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2014-07-22'
				},{
				name: ':',
				title: 'Digital Elevation Model 30m',
				originator: 'NASA',
                                format: 'image/png',
				group: '',
				visibility: false,
				metadata: 'http://aprgis.org/argis/metadata/adk_30m_dem.html',
				description: "30m DEM  produced by USGS SRTM (Shuttle Radar Topography Mission) in the year 2000.  Elevation units are meters.\n\nData Downloaded from USGS Seamless Data Distribution Site:\nhttp:\/\/seamless.usgs.gov\/website\/seamless\/viewer.php\nPost-processing performed by Steve Signell, Adirondack Ecological Center in Nov. 2005:\n \n1. Data tiles downloaded from USGS site\n2. Tiles reprojected to UTM 18N.\n3. Tiles mosaicked to create a coverage for the entire Adirondack park with a 10k buffer.\n4.  Several small voids due to mountain shadows were filled using values from the 30m NED downloaded from the USGS Seamless site.",
				styles: '',
				slds: [],
				cql_filter: null,
				queries: [],
                                updated: '2006-01-01'
				}]
						},
				wfs: '/geoserver/wfs'
				});